### PR TITLE
Clubs section (Life at NITJ) creation of frontend and backend

### PR DESCRIPTION
**Pull request by prash240303**
The following tasks have been completed in this pull request:
- Created the template.html file for clubs, incorporating a common proposed template.
- Modified the existing backend to accommodate club data in a new proposed format.
- Generated new credentials for clubs' heads/coordinators, granting them access to the admin panel for updating data.
- Provided all clubs with access to the super-admin, ensuring that only the clubs section is visible to roles (credentials) specific to each club in the admin panel.
- Updated the navbar by adding a ReadMore button for a comprehensive list of all clubs.
- Resolved the UI select menu issue in the navbar dashboard.
- Updated the Readme to include information about the Navbar dashboard route.

### CODE REVIEW

**Comment by prash240303** [comment]
- reverted the navbar changes. 
- reverted the news list changes 
- temporarily added the clubs data statically in the homepage (will fetch from DB when the new club's data is updated) --to prevent crash due to clubs schema changes

**Comment by harimurugan1989** [comment]
No file changes in navbar related things are allowed. 

Still some changes see coming.

**Comment by prash240303** [comment]
in the /public/js/data.js? (reason: the clubs DB schema needed modifications and I am not sure of validation of the data present in prod DB and new updated schema, so put all the data in the frontend only and commented the fetch from DB)

**Comment by harimurugan1989** [comment]
Merged. Check the deployment site and with concerned faculty coordinator approval, raise PR to deployment.

**Pull request merged**
