### PR TITLE
Revert "Deployment"

### PR DESCRIPTION
**Pull request by harimurugan1989**
Reverts wdmc-nitj/nitj-website-deploy#364

### CODE REVIEW

**Comment by parteekcoder** [comment]
@harimurugan1989 sir why this PR is reverted

**Comment by parteekcoder** [comment]
It contains changes from team C

**Comment by harimurugan1989** [comment]
@parteekcoder No one is supposed to push to deployment directly. It has to be pushed to main and then sync to deployment. We were unable to push to deployment because of Team C commits. Somehow we have corrected it. Later these commits are merged again to main! Chk the lastest code in repo. All these changes should be there. We reverted to match history and later merged. There is a merge from Gautham.. Chk it.

**Comment by parteekcoder** [comment]
This code is not in deployment branch

**Comment by harimurugan1989** [comment]
Do it again if it is not there. As far we checked no commits were deleted. Push to main only hereafter.

**Pull request merged**
